package projet.cpo;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author ramba
 */
public class IHMPrincipale extends javax.swing.JFrame {

    private final ArrayList<Ville> listeVilles;
    private ArrayList<Prevision> listePrevisions;
    private final String idVille;
    int xSouris, ySouris;

    /**
     * Creates new form IHMPrincipale
     * @param listeVilles
     * @param listePrevisions
     */
    public IHMPrincipale(ArrayList<Ville> listeVilles, ArrayList<Prevision> listePrevisions) {
        initComponents();
        this.listeVilles = listeVilles;
        this.listePrevisions = listePrevisions;
        this.idVille = listePrevisions.get(0).getId();
        
        listeVilleSelection.removeAllItems();
        for(int i=0; i<listeVilles.size(); i++){
            listeVilleSelection.addItem(listeVilles.get(i).getNom());
        }
        
        sliderPrevision.setMajorTickSpacing(1);
        sliderPrevision.setPaintTicks(true);
        
        
        ImageIcon image1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src\\projet\\cpo\\img\\humidity.png"));
        Image img1 = image1.getImage();
        Image img2 = img1.getScaledInstance(imgHumidite.getWidth(), imgHumidite.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgHumidite1 = new ImageIcon(img2);
        imgHumidite.setIcon(imgHumidite1);
        
        ImageIcon image2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src\\projet\\cpo\\img\\rain-2.png"));
        img1 = image2.getImage();
        img2 = img1.getScaledInstance(imgPrecipitation.getWidth(), imgPrecipitation.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgPrecipitation1 = new ImageIcon(img2);
        imgPrecipitation.setIcon(imgPrecipitation1);
        
        ImageIcon image3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src\\projet\\cpo\\img\\windometer.png"));
        img1 = image3.getImage();
        img2 = img1.getScaledInstance(imgWindspeed.getWidth(), imgWindspeed.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgWindspeed1 = new ImageIcon(img2);
        imgWindspeed.setIcon(imgWindspeed1);
        
        ImageIcon image4 = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src\\projet\\cpo\\img\\thermometer.png"));
        Image img3 = image4.getImage();
        Image img4 = img3.getScaledInstance(labelThermoPrevision.getWidth(), labelThermoPrevision.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon symbole1 = new ImageIcon(img4);
        labelThermoPrevision.setIcon(symbole1);
        
        ImageIcon image5 = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src\\projet\\cpo\\img\\humidity.png"));
        Image img5 = image5.getImage();
        Image img6 = img5.getScaledInstance(labelHumiditePrevision.getWidth(), labelHumiditePrevision.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon symbole2 = new ImageIcon(img6);
        labelHumiditePrevision.setIcon(symbole2);
        
        setPrevision();
        setPrevisionViaSlider(sliderPrevision.getValue());
        sliderPrevision.setValue(1);
        sliderPrevision.addChangeListener((ChangeEvent event) -> {
            setPrevisionViaSlider(sliderPrevision.getValue());
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        temp_actuel = new javax.swing.JLabel();
        labelDate_actuel = new javax.swing.JLabel();
        labelVilleTitre = new javax.swing.JLabel();
        listeVilleSelection = new javax.swing.JComboBox<>();
        boutonValiderVille = new javax.swing.JButton();
        labelSymbol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        precipitation_actuel = new javax.swing.JLabel();
        vitesseVent_actuel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        imgHumidite = new javax.swing.JLabel();
        imgWindspeed = new javax.swing.JLabel();
        imgPrecipitation = new javax.swing.JLabel();
        humidite_actuel = new javax.swing.JLabel();
        sliderPrevision = new javax.swing.JSlider();
        labelSymbolePrevision = new javax.swing.JLabel();
        humiditePrevision = new javax.swing.JLabel();
        labelDatePrevision = new javax.swing.JLabel();
        labelThermoPrevision = new javax.swing.JLabel();
        labelHumiditePrevision = new javax.swing.JLabel();
        tempPrevision = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        boutonQuitter = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 128, 178));
        jPanel1.setForeground(new java.awt.Color(52, 52, 52));

        temp_actuel.setFont(new java.awt.Font("Calibri Light", 0, 100)); // NOI18N
        temp_actuel.setForeground(new java.awt.Color(230, 230, 230));
        temp_actuel.setText("16,0 °");

        labelDate_actuel.setBackground(new java.awt.Color(255, 255, 255));
        labelDate_actuel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        labelDate_actuel.setForeground(new java.awt.Color(230, 230, 230));
        labelDate_actuel.setText("12 Mai 2020");

        labelVilleTitre.setBackground(new java.awt.Color(255, 255, 255));
        labelVilleTitre.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        labelVilleTitre.setForeground(new java.awt.Color(230, 230, 230));
        labelVilleTitre.setText("Troyes");

        listeVilleSelection.setBackground(new java.awt.Color(204, 204, 204));
        listeVilleSelection.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listeVilleSelection.setForeground(new java.awt.Color(51, 51, 51));
        listeVilleSelection.setMaximumRowCount(25);
        listeVilleSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listeVilleSelection.setBorder(null);
        listeVilleSelection.setLightWeightPopupEnabled(false);
        listeVilleSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeVilleSelectionActionPerformed(evt);
            }
        });

        boutonValiderVille.setBackground(new java.awt.Color(27, 128, 178));
        boutonValiderVille.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        boutonValiderVille.setForeground(new java.awt.Color(230, 230, 230));
        boutonValiderVille.setText("V A L I D E R");
        boutonValiderVille.setFocusPainted(false);
        boutonValiderVille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderVilleMouseClicked(evt);
            }
        });
        boutonValiderVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderVilleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listeVilleSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonValiderVille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDate_actuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(temp_actuel)
                                    .addComponent(labelSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelVilleTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeVilleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonValiderVille)
                .addGap(18, 18, 18)
                .addComponent(labelSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temp_actuel)
                .addGap(18, 18, 18)
                .addComponent(labelVilleTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDate_actuel)
                .addGap(46, 46, 46))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 580));

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));

        precipitation_actuel.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        precipitation_actuel.setForeground(new java.awt.Color(22, 22, 22));
        precipitation_actuel.setText("23 mm");

        vitesseVent_actuel.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        vitesseVent_actuel.setForeground(new java.awt.Color(22, 22, 22));
        vitesseVent_actuel.setText("5.7 m/s");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 22, 22));
        jLabel3.setText("D E T A I L");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 22, 22));
        jLabel4.setText("P R E V I S I O N S");

        humidite_actuel.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        humidite_actuel.setForeground(new java.awt.Color(22, 22, 22));
        humidite_actuel.setText("78 %");

        sliderPrevision.setBackground(new java.awt.Color(220, 220, 220));
        sliderPrevision.setMajorTickSpacing(1);
        sliderPrevision.setMaximum(30);
        sliderPrevision.setMinimum(1);
        sliderPrevision.setPaintTicks(true);
        sliderPrevision.setSnapToTicks(true);
        sliderPrevision.setValue(1);
        sliderPrevision.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        humiditePrevision.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        humiditePrevision.setForeground(new java.awt.Color(22, 22, 22));
        humiditePrevision.setText("17.0 °");

        labelDatePrevision.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        labelDatePrevision.setForeground(new java.awt.Color(22, 22, 22));
        labelDatePrevision.setText("13 Mai 2020, à 18 heures");

        tempPrevision.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        tempPrevision.setForeground(new java.awt.Color(22, 22, 22));
        tempPrevision.setText("17.0 °");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(224, 224, 224)
                                .addComponent(labelDatePrevision))
                            .addComponent(sliderPrevision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgHumidite, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humidite_actuel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgPrecipitation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precipitation_actuel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgWindspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vitesseVent_actuel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(labelSymbolePrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelThermoPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tempPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelHumiditePrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(humiditePrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imgHumidite, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(humidite_actuel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imgPrecipitation, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precipitation_actuel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imgWindspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vitesseVent_actuel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelDatePrevision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelThermoPrevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tempPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(humiditePrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHumiditePrevision, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelSymbolePrevision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(sliderPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 590, 580));

        jPanel3.setBackground(new java.awt.Color(22, 22, 22));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 230, 230));
        jLabel1.setText("M  E  T  E  O");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        boutonQuitter.setBackground(new java.awt.Color(153, 0, 0));
        boutonQuitter.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        boutonQuitter.setForeground(new java.awt.Color(255, 255, 255));
        boutonQuitter.setText("X");
        boutonQuitter.setBorderPainted(false);
        boutonQuitter.setDefaultCapable(false);
        boutonQuitter.setFocusPainted(false);
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frameDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frameDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeVilleSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeVilleSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listeVilleSelectionActionPerformed

    private void boutonValiderVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderVilleActionPerformed
        
    }//GEN-LAST:event_boutonValiderVilleActionPerformed
    
    
    
    private void boutonValiderVilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderVilleMouseClicked
        String nomVille = (String) listeVilleSelection.getSelectedItem();
        
        RecuperationPrevision recup = new RecuperationPrevision(listeVilles);
        recup.telechargerDepuisNom(nomVille);
        listePrevisions = recup.getTableauPrevision();
        setPrevision();
        setPrevisionViaSlider(sliderPrevision.getValue());
        sliderPrevision.setValue(1);
        sliderPrevision.addChangeListener((ChangeEvent event) -> {
            setPrevisionViaSlider(sliderPrevision.getValue());
        });
        
    }//GEN-LAST:event_boutonValiderVilleMouseClicked

    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boutonQuitterActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xSouris, y-ySouris);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xSouris = evt.getX();
        ySouris = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
        });
    }
    
    private void setPrevision(){
        String imgURL1 = "src\\projet\\cpo\\img\\" + listePrevisions.get(0).getSymbol() + ".png";
        String imgURL = imgURL1.replaceAll("\\s+","");
        ImageIcon image = new ImageIcon(Toolkit.getDefaultToolkit().getImage(imgURL));
        Image img1 = image.getImage();
        Image img2 = img1.getScaledInstance(labelSymbol.getWidth(), labelSymbol.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon symbole = new ImageIcon(img2);
        labelSymbol.setIcon(symbole);
        
        labelVilleTitre.setText(listePrevisions.get(0).getVille());
        labelDate_actuel.setText(listePrevisions.get(0).getDate().getJour() + " " + listePrevisions.get(0).getDate().getMoisLettre() + " " + listePrevisions.get(0).getDate().getAnnee());
        temp_actuel.setText(String.valueOf(listePrevisions.get(0).getTemp()).substring(0, 3) + "0 °");
        humidite_actuel.setText(String.valueOf(listePrevisions.get(0).getHumidite()).substring(0, 4) + " %");
        precipitation_actuel.setText(String.valueOf(listePrevisions.get(0).getPrecipitation()).substring(0, 3) + " mm");
        vitesseVent_actuel.setText(String.valueOf(listePrevisions.get(0).getVent_vitesse()).substring(0, 3) + " m/s");
    }
    
    private void setPrevisionViaSlider(int k){
        String imgURL2 = "src\\projet\\cpo\\img\\" + listePrevisions.get(k).getSymbol() + ".png";
        String imgURL3 = imgURL2.replaceAll("\\s+", "");
        ImageIcon image4 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(imgURL3));
        Image img3 = image4.getImage();
        Image img4 = img3.getScaledInstance(labelSymbolePrevision.getWidth(), labelSymbolePrevision.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon symbole1 = new ImageIcon(img4);
        labelSymbolePrevision.setIcon(symbole1);
        labelDatePrevision.setText(listePrevisions.get(k).getDate().getJour() + " " + listePrevisions.get(k).getDate().getMoisLettre() + " " + listePrevisions.get(k).getDate().getAnnee()+", "+listePrevisions.get(k).getDate().getHeure()+" heures");
        tempPrevision.setText(String.valueOf(listePrevisions.get(k).getTemp()).substring(0, 3) + "0 °");
        humiditePrevision.setText(String.valueOf(listePrevisions.get(k).getHumidite()).substring(0, 3) + "0 %");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonQuitter;
    private javax.swing.JButton boutonValiderVille;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel humiditePrevision;
    private javax.swing.JLabel humidite_actuel;
    private javax.swing.JLabel imgHumidite;
    private javax.swing.JLabel imgPrecipitation;
    private javax.swing.JLabel imgWindspeed;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDatePrevision;
    private javax.swing.JLabel labelDate_actuel;
    private javax.swing.JLabel labelHumiditePrevision;
    private javax.swing.JLabel labelSymbol;
    private javax.swing.JLabel labelSymbolePrevision;
    private javax.swing.JLabel labelThermoPrevision;
    private javax.swing.JLabel labelVilleTitre;
    private javax.swing.JComboBox<String> listeVilleSelection;
    private javax.swing.JLabel precipitation_actuel;
    private javax.swing.JSlider sliderPrevision;
    private javax.swing.JLabel tempPrevision;
    private javax.swing.JLabel temp_actuel;
    private javax.swing.JLabel vitesseVent_actuel;
    // End of variables declaration//GEN-END:variables
    
    

}
